<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SmartDocQA.Infrastructure</RootNamespace>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartDocQA.Domain\SmartDocQA.Domain.csproj" />
    <ProjectReference Include="..\SmartDocQA.Application\SmartDocQA.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Semantic Kernel -->
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Qdrant" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
    <PackageReference Include="PDFtoImage" />

  

    <!-- PDF + Word -->
     <PackageReference Include="UglyToad.PdfPig" />
    <PackageReference Include="DocumentFormat.OpenXml" />

    <!-- Azure -->
    <PackageReference Include="Azure.AI.FormRecognizer" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Identity" />

    <!-- Graph DB -->
      <PackageReference Include="Neo4j.Driver" />

    <!-- OneDrive -->
     <PackageReference Include="Microsoft.Graph" />

    <!-- Ollama -->
    <PackageReference Include="OllamaSharp" />

    <!-- SQLite — document registry -->
     <PackageReference Include="Microsoft.Data.Sqlite" />

    <!-- Resilience -->
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Guardrails\" />
  </ItemGroup>

</Project>
